name       : python-lsp-black
version    : 1.0.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/python-lsp-black/python-lsp-black-1.0.0.tar.gz : 0d7dd5f440a53b6f676fa8c097979e0ff611065b8f4ffd248b43228b0df2efee
homeage    : https://github.com/python-lsp/python-lsp-black
license    : MIT
component  : programming.python
summary    : Black plugin for the Python LSP Server
description: |
    Fork of the python-pyls-black project, maintained by the Spyder IDE team and the community. This is a Black plugin for the Python LSP Server.
rundeps    :
    - python-black
    - python-lsp-server
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
