name       : python-lsp-black
version    : 1.0.1
release    : 2
source     :
    - https://github.com/python-lsp/python-lsp-black/archive/refs/tags/v1.0.1.tar.gz : 432666772a642e45536af72da39f9437d46662ebca924247ab3776090edc7e22
homeage    : https://github.com/python-lsp/python-lsp-black
license    : MIT
component  : programming.python
summary    : Black plugin for the Python LSP Server
description: |
    Fork of the python-pyls-black project, maintained by the Spyder IDE team and the community. This is a Black plugin for the Python LSP Server.
rundeps    :
    - python-black
    - python-lsp-server
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
