name       : python-lsp-black
version    : 1.2.1
release    : 4
source     :
    - https://github.com/python-lsp/python-lsp-black/archive/refs/tags/v1.2.1.tar.gz : 1df12c5d3f6407040dd0020a918ed98b20c1ba68720e662f7c8044ed15f87186
homeage    : https://github.com/python-lsp/python-lsp-black
license    : MIT
component  : programming.python
summary    : Black plugin for the Python LSP Server
description: |
    Fork of the python-pyls-black project, maintained by the Spyder IDE team and the community. This is a Black plugin for the Python LSP Server.
rundeps    :
    - python-black
    - python-lsp-server
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
